'use strict';
const $=id=>document.getElementById(id);
const state={cases:[],caseId:null,session:null,trace:[],approvals:[],events:[],total:0,offset:0,search:'',busy:false,capabilities:null,tab:'evidence'};
const text=(tag,value,cls)=>{const el=document.createElement(tag);el.textContent=value;if(cls)el.className=cls;return el;};
const button=(label,handler,cls='subtle')=>{const b=text('button',label,cls);b.type='button';b.addEventListener('click',()=>safe(handler));return b;};
let toastTimer;
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,6000);}
async function safe(fn){try{await fn();}catch(e){toast(e.message);}}
async function api(path,body){const r=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(r.status===401)location.assign('/login');if(!r.ok)throw Error(data.error||'Request failed');return data;}
function tab(name){state.tab=name;const global=['matrix','tools','deployment'].includes(name);document.body.classList.toggle('catalog-mode',global);document.body.classList.toggle('framework-catalog',name==='frameworks'&&!state.busy);for(const n of ['evidence','trace','approvals','sessions','lab','frameworks','matrix','tools','deployment']){const view=$(n+'-view');if(view)view.hidden=n!==name;}document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));document.querySelectorAll('[data-workspace]').forEach(b=>{const active=b.dataset.workspace===(global?name:'evidence');b.classList.toggle('active',active);b.setAttribute('aria-current',active?'page':'false');});$('page-title').replaceChildren(text('span',global?catalogUI.sections[name][0]:'Investigations','page-title-text'));if(!global){const count=text('span',String(state.cases.length));count.id='case-count';$('page-title').append(count);}$('page-eyebrow').textContent=global?'WORKSPACE / CAPABILITY EXPLORER':'WORKSPACE / INVESTIGATIONS';$('page-description').textContent=global?catalogUI.sections[name][1]:'Evidence first. Every agent action accountable.';if(global)safe(()=>catalogUI.show(name));if(name==='sessions')safe(loadSessions);if(name==='lab')safe(()=>advancedUI.refresh());if(name==='frameworks')safe(()=>frameworkUI.refresh());}
function renderCases(){const q=$('case-search').value.toLowerCase();$('cases').replaceChildren();for(const c of state.cases.filter(c=>(c.title+' '+c.id).toLowerCase().includes(q))){const b=button('',()=>selectCase(c.id),'case'+(c.id===state.caseId?' selected':''));b.setAttribute('aria-current',String(c.id===state.caseId));const top=text('div','','case-top');top.append(text('span',c.id,'case-id'),text('span',c.severity,'severity '+c.severity));const meta=text('div','','case-meta');meta.append(text('span',c.event_count.toLocaleString()+' records'),text('span',c.asset_count+' hosts'));b.append(top,text('h3',c.title),meta);$('cases').append(b);}}
async function selectCase(id){if(state.busy)throw Error('Stop or finish the active run before switching cases.');state.caseId=id;state.session=null;state.trace=[];state.approvals=[];state.offset=0;state.search='';$('run-status').textContent='';$('event-search').value='';renderCases();renderSession();const c=state.cases.find(c=>c.id===id);const meta=text('div','','case-summary');meta.append(text('span',c.id),text('span','Open · review cohort'),text('span',c.asset_count+' observed hosts'));$('case-heading').replaceChildren(text('span',c.severity+' review priority','severity '+c.severity),text('h2',c.title),meta);tab('evidence');await loadEvidence();const sessions=await api('/api/sessions');const latest=sessions.find(s=>s.case_id===id);if(latest)await loadSession(latest.id);}
async function loadEvidence(){const selected=state.caseId;const data=await api('/api/events?'+new URLSearchParams({case_id:selected,limit:15,offset:state.offset,search:state.search}));if(state.caseId!==selected)return;state.events=data.items;state.total=data.total;$('evidence-count').textContent=data.total.toLocaleString()+' records · ordered by stable database ID';$('evidence').replaceChildren();for(const e of data.items){const row=document.createElement('tr');const id=document.createElement('td');id.append(text('strong','#'+e.id+' / Event '+e.event_id),text('small',e.occurred_at||'Timestamp not supplied'));const host=text('td',e.host||'Unknown');const source=text('td',e.source.replace('Microsoft-Windows-',''));const detail=document.createElement('td');const b=button('↗',()=>{ $('record-title').textContent='Record #'+e.id+' · '+e.host;$('raw-record').textContent=JSON.stringify(e,null,2);$('record-dialog').showModal();},'inspect');b.setAttribute('aria-label','Inspect record '+e.id);detail.append(b);row.append(id,host,source,detail);$('evidence').append(row);}$('page-info').textContent=data.total?`${state.offset+1}–${state.offset+data.items.length} of ${data.total.toLocaleString()}`:'No matching records';$('previous').disabled=state.offset===0;$('next').disabled=state.offset+15>=data.total;}
async function createSession(config={runtime:'simulator',permission:'read_only'}){state.session=await api('/api/sessions',{case_id:state.caseId,config});await loadSession(state.session.id);return state.session;}
async function ensureSession(){return state.session||await createSession();}
async function loadSession(id){if(state.busy)throw Error('A run is active.');const data=await api('/api/sessions/'+id);state.session=data.session;state.trace=data.trace;state.approvals=data.approvals;renderSession();}
function renderSession(){const s=state.session;$('session-label').textContent=s?s.id.slice(0,15)+'…':'New investigation';$('runtime-label').textContent=state.capabilities?.runtimes.find(r=>r.id===s?.config.runtime)?.name||'Deterministic replay';$('policy-label').textContent='◈ '+(s?.config.permission||'read_only').replaceAll('_',' ');$('usage').textContent=s?.config.runtime==='claude'?`SDK usage · ${s.input_tokens} input / ${s.output_tokens} output · $${s.cost_usd.toFixed(4)}`:s&&s.config.runtime!=='simulator'?`SDK usage · ${s.input_tokens} input / ${s.output_tokens} output · cost not reported`:'Replay mode · no model calls or token charges';renderMessages();renderTrace();renderApprovals();if(state.tab==='sessions')safe(loadSessions);}
function renderMessages(){const items=state.trace.filter(e=>['message.user','message.assistant'].includes(e.kind));$('messages').replaceChildren();if(!items.length){const empty=text('div','','empty');empty.append(text('span','✳'),text('h3','Start with the evidence'),text('p','Investigate this case. Inspect each tool call and approve changes yourself. Replay mode tests the harness without an LLM.'));$('messages').append(empty);}for(const e of items){const user=e.kind==='message.user';const box=text('div','','message'+(user?' user':''));box.append(text('span',user?'YOU':(e.payload.runtime||'agent').toUpperCase(),'message-label'),text('div',e.payload.text));$('messages').append(box);}$('messages').scrollTop=$('messages').scrollHeight;}
function renderTrace(){$('trace-count').textContent=state.trace.length;$('trace').replaceChildren();if(!state.trace.length)$('trace').append(text('p','Run an investigation to populate its audit trail.','muted'));for(const e of state.trace.filter(x=>x.kind!=='message.delta').slice(-150)){const d=document.createElement('details');d.className='trace-item';const summary=document.createElement('summary');summary.append(text('span',e.kind),text('small',new Date(e.created_at).toLocaleTimeString()));d.append(summary,text('pre',JSON.stringify(e.payload,null,2)));if(e.kind==='checkpoint')d.append(button('Branch from checkpoint',async()=>{if(state.busy)throw Error('Wait for the current run.');const child=await api('/api/sessions/'+state.session.id+'/fork',{seq:e.seq});await loadSession(child.id);toast('Created a conversation branch. No files or external actions were undone.');}));$('trace').append(d);}}
function renderApprovals(){const pending=state.approvals.filter(a=>a.status==='pending');$('approval-count').textContent=pending.length;$('approvals').replaceChildren();if(!state.approvals.length)$('approvals').append(text('p','No approvals requested in this session.','empty'));for(const a of state.approvals){const card=text('div','','approval-card');card.append(text('h3',a.tool),text('pre',JSON.stringify(a.arguments,null,2)),text('span',a.status,'muted'));if(a.status==='pending'){const buttons=text('div','','buttons');for(const decision of ['approve','deny'])buttons.append(button(decision==='approve'?'Approve once':'Deny',async()=>{await api('/api/sessions/'+state.session.id+'/approval',{id:a.id,decision});await advancedUI.sync();toast(decision==='approve'?'Approval recorded. Inspect the execution trace for completion.':'Action denied.');},decision==='approve'?'primary':'subtle'));card.append(buttons);}$('approvals').append(card);}}
async function loadSessions(){const list=await api('/api/sessions');$('sessions').replaceChildren();for(const s of list.filter(s=>s.case_id===state.caseId)){const b=button('',()=>loadSession(s.id),'session-card');const d=text('div');d.append(text('strong',s.title),text('small',s.config.runtime+' · '+s.config.permission+' · '+new Date(s.created_at).toLocaleString()));b.append(d,text('span',s.id===state.session?.id?'Current':'Resume →'));$('sessions').append(b);}if(!$('sessions').children.length)$('sessions').append(text('p','No saved sessions for this case yet.','empty'));}
function setBusy(value){state.busy=value;for(const id of ['send','new-session','configure','query','note','contain','compact'])$(id).disabled=value;$('stop').hidden=!value;$('prompt').disabled=value;}
async function send(message){if(state.busy||state.starting)return;state.starting=true;let s;try{s=await ensureSession();}finally{state.starting=false;}setBusy(true);$('prompt').value='';let failed=false;try{const response=await fetch('/api/sessions/'+s.id+'/messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message})});if(!response.ok)throw Error((await response.json()).error);const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='',partial='';while(true){const {value,done}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done});const lines=buffer.split('\n');buffer=lines.pop();for(const line of lines){if(!line)continue;const e=JSON.parse(line);if(!state.trace.some(t=>t.seq===e.seq))state.trace.push(e);state.trace.sort((a,b)=>a.seq-b.seq);if(e.kind==='approval.waiting'||e.kind==='input.waiting'){safe(()=>advancedUI.sync());tab(e.kind==='approval.waiting'?'approvals':'lab');}$('run-status').textContent=e.kind;if(e.kind==='run.failed'||e.kind==='run.cancelled'){failed=true;toast(e.payload.message);}if(e.kind==='message.delta'){partial+=e.payload.text;let draft=$('streaming-message');if(!draft){draft=text('div','','message');draft.id='streaming-message';$('messages').append(draft);}draft.textContent=partial;$('messages').scrollTop=$('messages').scrollHeight;$('run-status').textContent='Claude is responding…';}if(e.kind==='message.user'||e.kind==='message.assistant'){partial='';renderMessages();}renderTrace();}if(done)break;}}catch(error){failed=true;throw error;}finally{setBusy(false);await loadSession(s.id);$('run-status').textContent=failed?'Run stopped — see execution trace.':'Run complete · audit saved';}}
async function openSettings(){if(state.busy)throw Error('Wait for the active run.');$('settings').showModal();}
function setupSettings(){const cap=state.capabilities;$('runtime').replaceChildren();for(const r of cap.runtimes){const option=text('option',r.name+(r.available?'':' · unavailable'));option.value=r.id;option.disabled=!r.available;$('runtime').append(option);}const detail=()=>frameworkUI.selection();$('runtime').onchange=detail;detail();$('tool-settings').replaceChildren();for(const t of cap.tools){const row=text('div','','tool-option'),check=document.createElement('input');check.type='checkbox';check.checked=true;check.value=t.name;check.id='tool-'+t.name;const label=document.createElement('label');label.htmlFor=check.id;label.append(text('span',t.name),text('small',t.description));row.append(check,label);$('tool-settings').append(row);}}
let actionTool;
async function propose(toolName){await ensureSession();actionTool=toolName;$('action-title').textContent=toolName==='save_case_note'?'Propose a case note':'Simulate containment';$('action-help').textContent=toolName==='save_case_note'?'Save a local note after approval. Use a supervised session to enable writes.':'Dry-run only. This will never isolate an endpoint. Enter a host to record the proposed target.';$('action-value').value='';$('action-dialog').showModal();}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab));document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
$('case-search').oninput=renderCases;$('filter-form').onsubmit=e=>{e.preventDefault();state.search=$('event-search').value;state.offset=0;safe(loadEvidence);};$('previous').onclick=()=>safe(async()=>{state.offset=Math.max(0,state.offset-15);await loadEvidence();});$('next').onclick=()=>safe(async()=>{state.offset+=15;await loadEvidence();});
$('configure').onclick=()=>safe(openSettings);$('settings-nav').onclick=()=>safe(openSettings);$('new-session').onclick=()=>safe(openSettings);$('agent-nav').onclick=()=>{tab('evidence');document.querySelector('.agent').scrollIntoView({behavior:'smooth',block:'center'});$('prompt').focus();};$('cases-nav').onclick=()=>{tab('evidence');document.querySelector('.investigation').scrollIntoView({behavior:'smooth',block:'start'});};$('sessions-nav').onclick=()=>tab('sessions');
$('settings-form').onsubmit=e=>{e.preventDefault();safe(async()=>{await createSession({runtime:$('runtime').value,model:$('model').value,permission:$('permission').value,max_turns:Number($('max-turns').value),budget_usd:Number($('budget').value),max_output_tokens:Number($('output-tokens').value),thinking:$('thinking').value,accept_no_usd_cap:$('budget-ack').checked,structured_output:$('structured').checked,...advancedUI.config(),disabled_tools:[...document.querySelectorAll('#tool-settings input:not(:checked)')].map(c=>c.value)});$('settings').close();toast('Session created.');});};
$('chat-form').onsubmit=e=>{e.preventDefault();if($('prompt').value.trim())safe(()=>send($('prompt').value.trim()));};$('query').onclick=()=>safe(()=>send('Review the evidence in this case. Cite record IDs and separate observations from hypotheses.'));
$('stop').onclick=()=>safe(async()=>{await api('/api/sessions/'+state.session.id+'/cancel',{});toast('Cancellation requested.');});$('note').onclick=()=>safe(()=>propose('save_case_note'));$('contain').onclick=()=>safe(()=>propose('simulate_containment'));
$('action-form').onsubmit=e=>{e.preventDefault();safe(async()=>{const args=actionTool==='save_case_note'?{content:$('action-value').value}:{target:$('action-value').value};await api('/api/sessions/'+state.session.id+'/tool',{tool:actionTool,arguments:args});$('action-dialog').close();await loadSession(state.session.id);tab('approvals');});};
$('compact').onclick=()=>safe(async()=>{await ensureSession();await api('/api/sessions/'+state.session.id+'/compact',{});await loadSession(state.session.id);toast('Context checkpoint retained; full audit history preserved.');});
$('export').onclick=()=>safe(async()=>{if(!state.session)throw Error('Create a session first.');const data=await api('/api/sessions/'+state.session.id+'/export');const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=state.session.id+'.json';a.click();URL.revokeObjectURL(url);});
$('refresh').onclick=()=>safe(async()=>{if(state.busy)throw Error('An investigation is running.');await loadEvidence();if(state.session)await loadSession(state.session.id);await catalogUI.refresh();toast('Workspace and capability inventory refreshed.');});
window.addEventListener('DOMContentLoaded',()=>safe(async()=>{state.capabilities=await api('/api/capabilities');setupSettings();state.cases=await api('/api/incidents');$('case-count').textContent=state.cases.length;$('connection').textContent='Local database connected';await selectCase(state.cases[0].id);}));
